### ISSUE TITLE
Doesn't work with latest React v 18

### ISSUE THREAD

**Issue by amitdixit** [microsoft/azure-devops-extension-hot-reload-and-debug#62]
Doesn't work with latest React v 18. Kindly update the packages

**Comment by MatisseHack** [comment]
I think all packages are relatively up to date. Unfortunately React 16 is a peer dependency of [azure-devops-ui](https://github.com/microsoft/azure-devops-ui) so that package would need to be updated to support React 18.

I'm going to go ahead and close this issue for now since there's nothing more I can do at the moment in this repository, but feel free to open an issue on that repository if the issue persists.
